{
  "props": [],
  "components": {
    "file": {
      "type": "script\\FileScript",
      "x": 240.0,
      "y": 64.0,
      "props": {
        "path": "example.txt",
        "watch": "1"
      }
    },
    "zipFile": {
      "type": "bundle\\zip\\ZipFileScript",
      "x": 288.0,
      "y": 64.0,
      "props": {
        "path": "example.zip",
        "autoCreate": "1"
      }
    },
    "downloader": {
      "type": "bundle\\http\\HttpDownloader",
      "x": 128.0,
      "y": 64.0,
      "props": {
        "threadCount": "4"
      }
    },
    "httpClient": {
      "type": "bundle\\http\\HttpClient",
      "x": 192.0,
      "y": 64.0,
      "props": {
        "requestType": "URLENCODE",
        "responseType": "TEXT",
        "connectTimeout": "15000",
        "readTimeout": "0",
        "followRedirects": "1",
        "proxyType": "DIRECT",
        "userAgent": "QLLAuth"
      }
    }
  }
}